# Generated by Django 5.1.1 on 2024-09-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employeeId", models.PositiveIntegerField(null=True)),
                ("managerId", models.PositiveIntegerField(null=True)),
                ("employeeName", models.CharField(max_length=40, null=True)),
                ("managerName", models.CharField(max_length=40, null=True)),
                ("reviewDate", models.DateField(auto_now=True)),
                ("feedback", models.TextField(max_length=500)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pic/EmployeeProfilePic/",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("IT", "Information Technology"),
                            ("Finance", "Finance"),
                            ("Marketing", "Marketing"),
                            ("Operations", "Operations"),
                            ("Sales", "Sales"),
                        ],
                        max_length=50,
                    ),
                ),
                ("assignedManagerId", models.PositiveIntegerField(null=True)),
                ("hireDate", models.DateField(auto_now=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Leave", "On Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "total_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pic/ManagerProfilePic/",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=20, null=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("IT", "Information Technology"),
                            ("Finance", "Finance"),
                            ("Marketing", "Marketing"),
                            ("Operations", "Operations"),
                            ("Sales", "Sales"),
                        ],
                        default="HR",
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
