# Generated by Django 5.1.1 on 2024-09-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_task_delete_performancereview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="assignedManagerId",
        ),
        migrations.AddField(
            model_name="employee",
            name="assignedManager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.manager",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hireDate",
            field=models.DateField(auto_now_add=True),
        ),
    ]
