# Generated by Django 5.1.1 on 2024-09-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_remove_employee_assignedmanagerid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="assignedManager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="company.manager",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hireDate",
            field=models.DateField(auto_now=True),
        ),
    ]
